[2025-06-18T18:21:21.628+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T18:21:21.665+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_gcs_data_dag.load_data_from_gcs manual__2025-06-18T18:14:35.664615+00:00 [queued]>
[2025-06-18T18:21:21.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_gcs_data_dag.load_data_from_gcs manual__2025-06-18T18:14:35.664615+00:00 [queued]>
[2025-06-18T18:21:21.681+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-18T18:21:21.700+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_from_gcs> on 2025-06-18 18:14:35.664615+00:00
[2025-06-18T18:21:21.724+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=43) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-18T18:21:21.726+0000] {standard_task_runner.py:63} INFO - Started process 45 to run task
[2025-06-18T18:21:21.729+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_gcs_data_dag', 'load_data_from_gcs', 'manual__2025-06-18T18:14:35.664615+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/load_gcs_data_dag.py', '--cfg-path', '/tmp/tmpu84vwhfv']
[2025-06-18T18:21:21.733+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask load_data_from_gcs
[2025-06-18T18:21:21.823+0000] {task_command.py:426} INFO - Running <TaskInstance: load_gcs_data_dag.load_data_from_gcs manual__2025-06-18T18:14:35.664615+00:00 [running]> on host 3e2a7fb3b426
[2025-06-18T18:21:22.010+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_gcs_data_dag' AIRFLOW_CTX_TASK_ID='load_data_from_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T18:14:35.664615+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T18:14:35.664615+00:00'
[2025-06-18T18:21:22.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T18:21:22.131+0000] {logging_mixin.py:188} INFO - ▶ 탐색 중: votes/
[2025-06-18T18:21:24.431+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T18:21:24.436+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_gcs_data_dag.py", line 40, in load_gcs_data
    df.to_parquet(local_file_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 2970, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 483, in to_parquet
    impl.write(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 197, in write
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/raw/accounts_attendance.parquet'
[2025-06-18T18:21:24.490+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_gcs_data_dag, task_id=load_data_from_gcs, run_id=manual__2025-06-18T18:14:35.664615+00:00, execution_date=20250618T181435, start_date=20250618T182121, end_date=20250618T182124
[2025-06-18T18:21:24.513+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task load_data_from_gcs ([Errno 13] Permission denied: '/opt/airflow/data/raw/accounts_attendance.parquet'; 45)
[2025-06-18T18:21:24.581+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T18:21:24.608+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T18:21:24.612+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
