[2025-06-18T15:28:50.668+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T15:28:50.690+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_gcs_data_dag.load_data_from_gcs manual__2025-06-18T14:56:52.539495+00:00 [queued]>
[2025-06-18T15:28:50.698+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_gcs_data_dag.load_data_from_gcs manual__2025-06-18T14:56:52.539495+00:00 [queued]>
[2025-06-18T15:28:50.699+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-18T15:28:50.712+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_from_gcs> on 2025-06-18 14:56:52.539495+00:00
[2025-06-18T15:28:50.727+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=41) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-18T15:28:50.729+0000] {standard_task_runner.py:63} INFO - Started process 43 to run task
[2025-06-18T15:28:50.728+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_gcs_data_dag', 'load_data_from_gcs', 'manual__2025-06-18T14:56:52.539495+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/load_gcs_data_dag.py', '--cfg-path', '/tmp/tmpl6ubxw1x']
[2025-06-18T15:28:50.730+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask load_data_from_gcs
[2025-06-18T15:28:50.775+0000] {task_command.py:426} INFO - Running <TaskInstance: load_gcs_data_dag.load_data_from_gcs manual__2025-06-18T14:56:52.539495+00:00 [running]> on host 9d2be549d26b
[2025-06-18T15:28:50.871+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_gcs_data_dag' AIRFLOW_CTX_TASK_ID='load_data_from_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T14:56:52.539495+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T14:56:52.539495+00:00'
[2025-06-18T15:28:50.873+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T15:28:53.108+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_attendance.parquet → /opt/***/data/raw/accounts_attendance.parquet
[2025-06-18T15:28:53.716+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_blockrecord.parquet → /opt/***/data/raw/accounts_blockrecord.parquet
[2025-06-18T15:28:54.230+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_failpaymenthistory.parquet → /opt/***/data/raw/accounts_failpaymenthistory.parquet
[2025-06-18T15:29:09.476+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_friendrequest.parquet → /opt/***/data/raw/accounts_friendrequest.parquet
[2025-06-18T15:29:10.080+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_group.parquet → /opt/***/data/raw/accounts_group.parquet
[2025-06-18T15:29:10.686+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_nearbyschool.parquet → /opt/***/data/raw/accounts_nearbyschool.parquet
[2025-06-18T15:29:11.364+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_paymenthistory.parquet → /opt/***/data/raw/accounts_paymenthistory.parquet
[2025-06-18T15:29:13.015+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_pointhistory.parquet → /opt/***/data/raw/accounts_pointhistory.parquet
[2025-06-18T15:29:13.510+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_school.parquet → /opt/***/data/raw/accounts_school.parquet
[2025-06-18T15:29:13.940+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_timelinereport.parquet → /opt/***/data/raw/accounts_timelinereport.parquet
[2025-06-18T15:29:22.332+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_user.parquet → /opt/***/data/raw/accounts_user.parquet
[2025-06-18T15:29:22.956+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_user_contacts.parquet → /opt/***/data/raw/accounts_user_contacts.parquet
[2025-06-18T15:29:24.822+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_userquestionrecord.parquet → /opt/***/data/raw/accounts_userquestionrecord.parquet
[2025-06-18T15:29:25.419+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/accounts_userwithdraw.parquet → /opt/***/data/raw/accounts_userwithdraw.parquet
[2025-06-18T15:29:25.844+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/event_receipts.parquet → /opt/***/data/raw/event_receipts.parquet
[2025-06-18T15:29:26.312+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/events.parquet → /opt/***/data/raw/events.parquet
[2025-06-18T15:29:26.856+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/polls_question.parquet → /opt/***/data/raw/polls_question.parquet
[2025-06-18T15:29:27.873+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/polls_questionpiece.parquet → /opt/***/data/raw/polls_questionpiece.parquet
[2025-06-18T15:29:28.464+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/polls_questionreport.parquet → /opt/***/data/raw/polls_questionreport.parquet
[2025-06-18T15:29:29.483+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/polls_questionset.parquet → /opt/***/data/raw/polls_questionset.parquet
[2025-06-18T15:29:31.983+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/votes/polls_usercandidate.parquet → /opt/***/data/raw/polls_usercandidate.parquet
[2025-06-18T15:30:07.142+0000] {logging_mixin.py:188} INFO - [✅ 저장 완료] gs://my-advanced_data-bucket/hackle_final/final.parquet → /opt/***/data/raw/final.parquet
[2025-06-18T15:33:14.712+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.5), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 213, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 258, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1821, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 510, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1807, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres" (172.18.0.5), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-18T15:33:47.905+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-06-18T15:36:04.788+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-06-18T15:36:16.228+0000] {local_task_job_runner.py:214} ERROR - Heartbeat time limit exceeded!
[2025-06-18T15:36:27.417+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-18T15:36:54.063+0000] {process_utils.py:132} INFO - Sending 15 to group 43. PIDs of all processes in the group: [43]
[2025-06-18T15:36:57.665+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 43
[2025-06-18T15:38:37.833+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=43, name='airflow task ru', status='sleeping', started='15:28:50') did not respond to SIGTERM. Trying SIGKILL
[2025-06-18T15:38:54.042+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 43
[2025-06-18T15:38:58.746+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=43, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='15:28:50') (43) terminated with exit code -9
[2025-06-18T15:38:58.756+0000] {standard_task_runner.py:178} ERROR - Job 42 was killed before it finished (likely due to running out of memory)
